---
- hosts: '127.0.0.1'
  connection: 'local'
  vars:
    ghe_env:
      SNAPSHOTS_OLDER_THAN_DAYS: 3

  tasks:
    - name: Find EC2 instances that have volumes to snapshot
      ec2_remote_facts:
        region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"
        filters:
          instance-state-name: running
          "tag:EBS_backup": 'true'
      register: ec2

    - name: Find all attached volumes
      ec2_vol:
        instance: "{{ item.id }}"
        region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"
        state: list
      with_items: "{{ ec2.instances }}"
      register: ec2_volumes

    - name: Flatten the volumes list
      set_fact:
        volumes: "{{ ec2_volumes.results|map(attribute='volumes')|list }}"

    - include: take_snapshot.yml
      vars:
        volume: "{{ item }}"
      with_items: "{{ volumes }}"

    - name: 'Delete older Github Enterprise snapshots'
      environment: "{{ ghe_env }}"
      command: 'python prune_snapshots.py'
